# Generated by Django 5.1.7 on 2025-03-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='district name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='district name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='district name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='district name')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('address_uz', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('rooms', models.IntegerField(verbose_name='rooms')),
                ('floor', models.IntegerField(verbose_name='floor')),
                ('total_floor', models.IntegerField(verbose_name='total_floor')),
                ('area', models.FloatField(verbose_name='area')),
                ('furnished', models.BooleanField(default=False, verbose_name='furnished')),
                ('price_day', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='price_day')),
                ('price_week', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='price_week')),
                ('price_year', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='price_year')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('archived', 'Archived')], default='archived', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='region name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='region name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='region name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='region name')),
            ],
        ),
    ]
